spring:
  datasource:
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5432/cafecms
  jpa:
    hibernate:
      ddl-auto:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  liquibase:
    change-log: db.changelog/db.changelog-master.xml
